name: Deploy static site to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload static content
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      # ✅ Explicitly include upload-artifact to resolve dependency
      - name: Ensure artifact upload available
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: ./.github/workflows/static.yml

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
